POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Este es el mejor blog!!!!",
  "author": "Juan",
  "url": "elblogdejuan.com"
}


###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Juan"
}